apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-management-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quote-management-ms
  template:
    metadata:
      labels:
        app: quote-management-ms
    spec:
      containers:
        - name: quote-management-ms
          image: 891377328281.dkr.ecr.us-east-1.amazonaws.com/quote_management_ms:latest
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: quote-management-ms
spec:
  selector:
    app: quote-management-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
